/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_006_081;

import controller.PesanTiketController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.Connector;
import javax.swing.*;

/**
 *
 * @author Acer
 */
public class FormPemesananView extends javax.swing.JFrame {

    public String nama_depan, nama_belakang, no_ktp;

    Connector connector = new Connector();    
    
    public FormPemesananView() {
        initComponents();
        setTitle("Form Pemesanan");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pesan = new javax.swing.JButton();
        tfNamaDepan = new javax.swing.JTextField();
        tfNamaBelakang = new javax.swing.JTextField();
        tfHP = new javax.swing.JTextField();
        tfKTP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_006_081/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("ISI DATA PEMESAN TIKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setText("Nama Depan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel3.setText("Nama Belakang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        jLabel4.setText("No. KTP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));

        jLabel5.setText("No. Hp");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, -1));

        Pesan.setText("Pesan & Cetak Tiket");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        tfNamaDepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaDepanActionPerformed(evt);
            }
        });
        getContentPane().add(tfNamaDepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, -1));

        tfNamaBelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaBelakangActionPerformed(evt);
            }
        });
        getContentPane().add(tfNamaBelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, -1));

        tfHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHPActionPerformed(evt);
            }
        });
        getContentPane().add(tfHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, -1));

        tfKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKTPActionPerformed(evt);
            }
        });
        getContentPane().add(tfKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_006_081/wing-airplane-flying-clouds.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaDepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaDepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaDepanActionPerformed

    private void tfNamaBelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaBelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaBelakangActionPerformed

    private void tfHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHPActionPerformed

    private void tfKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKTPActionPerformed

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
         
    }//GEN-LAST:event_PesanActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPemesananView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Pesan;
    public javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfHP;
    private javax.swing.JTextField tfKTP;
    private javax.swing.JTextField tfNamaBelakang;
    private javax.swing.JTextField tfNamaDepan;
    // End of variables declaration//GEN-END:variables
    public String getNama_depan() {
        return tfNamaDepan.getText();
    }

    public String getNama_belakang() {
        return tfNamaBelakang.getText();
    }

    public String getKtp() {
        return tfKTP.getText();
    }
    
    public String getHp() {
        return tfHP.getText();
    }
}
